global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'springbootjavasdk'
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8081'
        labels:
          group: 'spring-boot-metrics'