server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  # temporal specific configs
  temporal:
    namespace: ${tmprl.cloud.namespace}
    connection:
      target: ${tmprl.cloud.target}
      enable-https: true
    # (Note following configuration are not set by default but serve more as reference)
    #    workers:
    #      - task-queue: DemoTaskQueue
    #        capacity:
    #          max-concurrent-workflow-task-pollers: 6
    #          max-concurrent-activity-task-pollers: 6
    #        rate-limits:
    #          max-worker-activities-per-second: 3
    #          max-task-queue-activities-per-second: 3
    #    workflow-cache:
    #      max-instances: 10
    #      max-threads: 10
    workersAutoDiscovery:
      packages: com.samples.demo
  # docker deployment
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
# temporal cloud config
tmprl:
  cloud:
   key: <your_api_key>
   target: <your_cloud_target>
   namespace: <your_cloud_namespace>
# actuator (sdk metrics)
management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      group:
        liveness:
          include: livenessstate,cacheCheck
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
tracing:
  url: http://localhost:4317
