{
 "title": "Replay25 SDK Worker Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Started Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_total{operation=\"StartWorkflowExecution\"}[1m])) by (namespace, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(temporal_workflow_completed_total[1m])) by (namespace) or vector(0)",
     "legendFormat": "NS: {{namespace}}"
    }
   ]
  },
  {
   "title": "Requests by operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_total[1m])) by (namespace, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_failure[1m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Task Schedule to Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[$__rate_interval])) by (namespace, le))",
     "legendFormat": "NS: {{namespace}} "
    }
   ]
  },
  {
   "title": "Activity Schedule to Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_seconds_bucket[$__rate_interval])) by (namespace, task_queue, activity_type, le))",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}} ACT: {{activity_type}}"
    }
   ]
  },
  {
   "title": "Worker Task Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(avg_over_time(temporal_worker_task_slots_available[1m])) by (worker_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Task Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(avg_over_time(workflow_task_execution_failed_total[1m])) by (namespace)",
     "legendFormat": "NS: {{namespace}} TQ:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Sticky Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(max_over_time(temporal_sticky_cache_size[1m])) by(namespace)",
     "legendFormat": "NS: {{namespace}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_latency_seconds_max{namespace!=\"none\"}[1m])) by (namespace, task_queue)",
     "legendFormat": "NS: {{namespace}} TQ: {{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(workflow_task_backlog[1m])) by (namespace, task_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity Task Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(activity_task_backlog[1m])) by (namespace, task_queue)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}